# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'classify_image']

# %% ../app.ipynb 1
from fastai.vision.all import *
import gradio as gr


# %% ../app.ipynb 3
learn = load_learner('model.pkl')

# %% ../app.ipynb 6
categories = ('Arcus','Cataract','Conjuctivities','Eye Melanoma(Eye Cancer)','Normal Eye')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories,map(float,probs)))


# %% ../app.ipynb 8
image = gr.inputs.Image(shape=(192,192))
label = gr.outputs.Label()
examples = ['arcus.jpg','c.jpg','nik.jpg','conjuc.jpg','eyec.jpeg']

intf = gr.Interface(fn = classify_image,inputs = image,outputs = label,examples= examples)
intf.launch(inline=False)
